-- AlterTable
ALTER TABLE "Customer" ADD COLUMN IF NOT EXISTS "state" TEXT;

-- AlterTable
ALTER TABLE "Invoice" ADD COLUMN IF NOT EXISTS "taxType" TEXT NOT NULL DEFAULT 'INTRASTATE';
ALTER TABLE "Invoice" ADD COLUMN IF NOT EXISTS "igstTotal" DECIMAL(10,2) NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "InvoiceItem" ADD COLUMN IF NOT EXISTS "igstAmount" DECIMAL(10,2) NOT NULL DEFAULT 0;
