services:
  - type: web
    name: prathna-billing-backend
    runtime: node
    plan: free
    rootDir: server
    buildCommand: npm install && npx prisma generate
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: DATABASE_URL
        value: postgresql://postgres.aropeqsqfwbrhyfyeekw:prathna-enterprise@aws-0-ap-northeast-1.pooler.supabase.com:6543/postgres?pgbouncer=true&connection_limit=1
      - key: DIRECT_URL
        value: postgresql://postgres.aropeqsqfwbrhyfyeekw:prathna-enterprise@aws-0-ap-northeast-1.pooler.supabase.com:5432/postgres
      - key: JWT_SECRET
        value: 089441f64633038f3363fc0e185d30e6f1ea7d41f559af015b9af750a4bf208753091f9c4e1d65edc1fbc0a26f7d5d95e792cd5b73ddf44d81e6994c1ac7d1f4
      - key: CORS_ORIGIN
        value: https://prathna-billing.vercel.app
